### ISSUE TITLE
Where are the emotion and action embeddings?

### ISSUE THREAD

**Issue by kasanari** [roholazandie/EmpTransfo#1]
In your report you mention using additional embeddings for emotions and actions. I can not find any reference to these in the source code. Are they missing, or named something non-obvious?

**Comment by RORO-ML** [comment]
Can't find them either, could you please help us out?

**Comment by roholazandie** [comment]
You can find them in [train_multihead.py](https://github.com/roholazandie/EmpTransfo/blob/master/train_multihead.py) on line 92 and 93. Let me know if this is what you're looking for.

**Comment by kasanari** [comment]
Thank you, I was looking for the embedding layers and with that info I managed to find them. They are on lines 618 and 619 in [modeling_openai.py](https://github.com/roholazandie/EmpTransfo/blob/master/pytorch_pretrained_bert/modeling_openai.py) for anyone else who is looking for them.
