### ISSUE TITLE
dialog act classification

### ISSUE THREAD

**Issue by D4sh12** [roholazandie/EmpTransfo#4]
Hello.
I'm trying to fine-tune the model with new dataset, I'm searching for dialog act classification for "candidates_acts", would you recommending a good model.
thanks for help!

**Comment by roholazandie** [comment]
Hi,
If you want to use classification for dialog acts your best bet is using huggingface text classification. This is a good start
https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/multiple_choice.ipynb
let me know if that works for you and I understood your question properly

**Comment by D4sh12** [comment]
> Hi, If you want to use classification for dialog acts your best bet is using huggingface text classification. This is a good start https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/multiple_choice.ipynb let me know if that works for you and I understood your question properly

Yep! 
I read it, and trained BERT text classification model using a Dialog Act Dataset.
Thank you for helping me Out
